#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
#include <cmath>
#include <complex>
#include <ctime>
#include <vector>
#include <map>
#include <utility>
#include <armadillo>

#include "omp.h"
#include "Tricubic3.h"
#include "Constants.h"
#include "typedef.h"
#include "Laser.h"
#include "RK.h"
#include "Loading_parameters.h"
#include "Observables.h"
#include "ReadInput.h"
#include "Continuum.h"
#include "RK_Cont.h"
